# Site settings
title: Website-title
email: your.email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  this is a m ulti-line
  description
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yourTwiterHandle
github_username:  yourGithubHandle

# Build settings
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]
sass:
  sass_dir: resources/css/sass
